spring:
  application:
    name: ServiceSystemB
    
  # freemarker
  freemarker: 
    request-context-attribute: request
    allow-request-override: false
    cache: false
    charset: UTF-8
    expose-request-attributes: true
    expose-session-attributes: true
    suffix: .ftl
    
eureka:
  client:
    service-url: 
      defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/
  instance:
    status-page-url-path: /info 
    health-check-url-path: /health 
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2